run_id: STL10_NIN_experiment1

#model params
model: 'resnet18'
model_params:
  num_classes: 4
  num_stages: 4


#dataset params:
dataset: 'STL10'
dataset_params:
  batch_size: 128
  image_size: 96
  loader_mode: normal

#train params:
train:
  epochs: 100

#optimizer params:
optimizer: 'SGD'
optimizer_params:
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  
# Standards:
# Name 'xxx' defined in first-level, Params defined in second-level, called by eval('xxx')(**yyy)
